docs/contributing/introduction-to-contributing.md

This PR fixes 3/4 points from #36. Considering the 2nd point, `In the "Testing" section...` is not a big issue.

fix: improve intro to contributing

---

docs/chrome-extension/project-utilities.md
sidebars.js

As suggested in https://github.com/open-sauced/browser-extensions/pull/64#issuecomment-1534845825,  this PR adds a `Project utilities` section to the `Chrome extension` category of the docs that presents concise explanations about some of the project's utility functions.

docs: Added extension-utilities-docs

---

docs/chrome-extension/using-the-chrome-extension.md

This adds the details and information of using post to highlight and AI configuration. 
fixes #93

chore: add post to highlight and AI settings

---

docs/contributing/introduction-to-contributing.md
docs/introduction.md

This PR adds to the Contributing Guide
Fixes #102 
N/A

feat: Add FAQ section to Contributing Guide 

---

docs/contributing/introduction-to-contributing.md

Fixes typos in the Intro to contribution's faq section by adding spaces. Added space in between "out" and "this" for bullet point 1 and "our" and "Feedback" for bullet point 3
Fixes #113
Before:
After:

fix: add missing spaces in faq

---

docs/technical/resolve-merge-conflicts.md

This PR fixes a typo in `npm-shrinkwrap.json` in the Resolve Merge Conflicts section.
Fixes #125

fix: Correct typo in resolve-merge-conflicts.md

---

docs/community/faqs.md

Update the link in the faq.md file for "How do I find good first issues?" to [this guide from freeCodeCamp](https://www.freecodecamp.org/news/how-to-find-good-first-issues-on-github/) instead of the previous YouTube video. This guide provides more comprehensive information on finding good first issues on GitHub.
Fixes #140
Before:
https://github.com/open-sauced/docs/assets/106407013/4208a33a-0b0f-4c52-a5e7-f1abc7af81b7
After:
https://github.com/open-sauced/docs/assets/106407013/f2afa8d4-9a08-4ac2-8e5e-79154a791b99

docs: replace url for finding good first issue

---

docs/contributing/introduction-to-contributing.md

This PR updates the license language in the contributors guide to reflect the fact that different repos use different licenses. The exact language is only a suggestion and I'm happy to change it.
Fixes #139 
No.

fix: Update license language in contributing guide

---

docs/technical/resolve-merge-conflicts.md
docs/technical/setup-repo-with-git.md
sidebars.js

The following PR is responsible for moving the setting up repo with Git out of the merge conflicts section into its own section.
Now under the Technical Guide section, there is a new section for how to setup a repo with Git, GitHub and GitHub CLI.
I also added some missing setup instructions for the GitHub CLI section so it is more informative for beginners. 
closes #124

feat: creating separate section for setting up repo with Git

---

.gitignore
docusaurus.config.js

The PR fixes the docs search issue with Algolia
Didn’t see a need to add markprompt to the implementation as [algolia DocSearch](https://docsearch.algolia.com/) alone was able to fix the search. Thanks @Ant-Shell for the helpful resources you provided, it all made the fix faster👍
closes #95 
https://github.com/open-sauced/docs/assets/62995161/490d446e-4f90-403e-8500-30acc3fbbfb4
https://github.com/open-sauced/docs/assets/62995161/596f4d0d-256b-40c9-b11a-4bda0362973b

feat: add algolia search functionality to docs

---

docs/community/faqs.md
docs/features/lists.md

Add Team Sync directions to FAQs
closes #206

docs: Add Team Sync instructions to FAQs

---

docs/community/glossary.md
sidebars.js

This PR adds a glossary feature to OpenSauced's docs in getting started section under community.
[Fixes #200 ](https://github.com/open-sauced/docs/issues/200)

feat: adds glossary 

---

docusaurus.config.js
netlify.toml

closes #307 
Using the deploy preview in the next.config.js file works:
https://github.com/open-sauced/docs/assets/34313413/95ce7a42-da41-424e-8c10-e2d6eaf2a64b

fix: Change base url for subdirectory

---

docs/contributing/opensauced-writers-guide/how-to-add-your-post.md
sidebars.js

This adds a guide for writers to add their posts to our community-resources section.
closes #320 
Running locally: http://localhost:3000/contributing/opensauced-writers-guide/writers-guide/

feat: Add blog guide for posting to our community resources

---

.github/workflows/release.yml
blog/2023/2023-08-07-you-dont-need-a-mentor-embracing-the-power-of-community.md
blog/2023/2023-09-27-open-source-abcs-transparency.md
blog/2023/2023-10-03-how-to-be-a-top-contributor-this-hacktoberfest.md
docs/features/repo-pages.md
docs/welcome/glossary.md
npm-shrinkwrap.json
package.json

adds info to repo pages and glossary on contrib confidence.
Note: I'm not sure this is the best approach, but I wanted to get something in so I'm not blocking the repo page merge
closes #329 
https://deploy-preview-330--saucedocs.netlify.app/features/repo-pages/#insights-into-contributor-confidence

feat: add contrib confidence

---

blog/2024/2024-06-17-valibot-a-new-approach-to-data-validation-in-javascript.md

Made some updates to the [blog post on Valibot](https://opensauced.pizza/docs/community-resources/valibot-a-new-approach-to-data-validation-in-javascript/) after getting some feedback from the creator, Fabian Hiller.
Relates to #328

chore: updated valibot blog post with feedback from Fabian Hiller

---

docs/features/repo-pages.md
docs/features/workspaces.md

- Adds tip to repo pages about how to add to a workspace
- Adds StarSearch to Workspace
closes #353 
closes #351

feat: workspace upgrades

---

docs/features/repo-pages.md
docs/welcome/glossary.md

- adds OSSF to repo pages and glossary
closes #355
1. go to /features/repo-pages
2. See OSSF scorecard entry

feat: ossf

---

blog/2024/2024-08-05-open-source-challenge.md

Adds my latest blog post on 100days challenge
closes #361 
1. Go to /community-resources/100-days-of-oss-challenge
2. See truncated post

feat: Add new blog post on 100daysofoss challenge

---

docs/features/repo-pages.md

Adds info on SBOM to docs
closes #369 
1. Go to /features/repo-pages/

feat: Add SBOM to docs

---

docusaurus.config.js
npm-shrinkwrap.json
package.json

Integrates PostHog into the docs using the `posthog-docusaurus` plugin to get autocapture events and analytics.
Closes #380 
1. Go throughout different pages in the docs
2. Go to PostHog and into the 'Docs' projects
3. See that your navigation on the pages are captured as an event

feat: integrate PostHog for analytics

---

.gitignore
docs/opensauced-guides/oscr-score-guide/oscr-introduction.md
docs/welcome/faqs.md
sidebars.js

This adds a section explaining what OSCR is and showing ways to improve it.
Fixes #368 
N/A
N/A

docs: how OSCR is calculated and how to improve it

---

blog/2023/2023-09-21-supercharge-your-repository-with-code-owners.md
blog/2023/2023-10-31-github-actions-a-maintainers-best-friend.md
blog/2023/2023-11-14-boost-productivity-with-the-github-cli.md
blog/2023/2023-12-14-migrating-from-jest-to-vitest-for-your-react-application.md
blog/2024/2024-01-23-the-native-browser-dialog-element.md
blog/2024/2024-02-06-challenging-the-skeptics-unveiling-the-undeniable-goodness-of-tailwind-css.md
blog/2024/2024-03-14-stuck-in-the-middle-with-you-an-intro-to-middleware.md
blog/2024/2024-04-02-form-and-function-how-i-lost-my-submit-button-got-it-back.md
blog/2024/2024-04-16-creating-an-og-image-using-react-and-netlify-edge-functions.md

- Added truncate after the first or second paragraph
- Added missing `,` in the first paragraph of `blog/2024/2024-04-02-form-and-function-how-i-lost-my-submit-button-got-it-back.md`
Closes #405 
Before
After
1. Go to the `Community Resources` tab on docs
2. Now you will see truncate post with Read more option

docs: add truncate markers to blog posts for improved excerpts

---

docs/welcome/key-metrics-guide.md
sidebars.js

This PR adds a key metrics guide section to the documentation.
Fixes #407
N/A
1. Run the project locally
2. Notice the new sidebar entry under the "Getting Started" section.
3. See that all the mentioned metrics are covered.

feat: add section for key metrics guide
