open-sauced/docs

- docusaurus.config.js
- npm-shrinkwrap.json
- package.json
> feat: re-add algolia search

- .github/workflows/triage.yml
This PR adds `.take` command.
closes [#4](https://github.com/open-sauced/semantic-release-conventional-config/issues/4)
> ci: add open-sauced triage workflows

- docs/contributing/fetching-data-from-github.md
This PR adds docs on the stars.json features 
https://github.com/open-sauced/open-sauced/pull/1124
> docs: Adds note about data.json and stars.json

- .github/workflows/development.yml
- .github/workflows/release.yml
- Dockerfile
- docs/maintainers/check-engines.md
- docs/maintainers/semantic-release.md
- docs/maintainers/setup.md
- docusaurus.config.js
- sidebars.js
- [] ♻️ Refactor
This PR adds a lot of documentation on open sauced tooling and some minor bug fixes that would have taken too long to merge if we went the triage way - sorry folks, you missed out on opening more hacktoberfest issues!
Closes #11 
Praise the 🍕
> feat: add missing contributing docs

- Dockerfile
This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 
corrects deploy for #8 and #11
> fix: correct npm install in docker container

- .github/workflows/compliance.yml
- .github/workflows/development.yml
- .github/workflows/release.yml
- README.md
- docusaurus.config.js
- npm-shrinkwrap.json
- package.json
- static/CNAME
This PR creates a pdf handbook out of the docs site.
Example: 
- run: https://github.com/0-vortex/open-sauced-docs-test/runs/4121252869?check_suite_focus=true
- deploy: https://open-sauced-docs-test.vortex.name
- pdf: https://open-sauced-docs-test.vortex.name/open-sauced-docs.pdf
> ci: add docusaurus-prince-pdf generation

- npm-shrinkwrap.json
- package.json
This PR implements [@open-sauced/conventional-commit](https://github.com/open-sauced/conventional-commit). 
closes #25
> feat: implement @open-sauced/conventional commit

- README.md
- npm-shrinkwrap.json
- package.json
This PR updates the contributing link.
closes #33
> docs: correct contributing link

- .czrc
- .github/workflows/release.yml
- docs/maintainers/conventional-commit.md
- docs/maintainers/semantic-release.md
- npm-shrinkwrap.json
- package.json
- release.config.js
- sidebars.js
- adds [@open-sauced/conventional-commit](https://github.com/open-sauced/conventional-commit) documentation
- updates [@open-sauced/semantic-release-conventional-config](https://github.com/open-sauced/semantic-release-conventional-config) docs
- implements isolated `open-sauced/semantic-release-conventional-config` release process
closes #26
closes #30
closes #31
> docs: add release docs for open-sauced/conventional-commit

- LICENSE
This PR fixes https://github.com/open-sauced/semantic-release-conventional-config/issues/25 locally
> fix: workaround license check by adding license

- docs/contributing/introduction-to-contributing.md
> docs: Adding Testing JavaScript link

- docs/contributing/introduction-to-contributing.md
minor grammatical error fix that I noticed while reading through the online documentation for the contribution guide
Fixes issue raised at #42 
[Scandinavian Flick](https://i.imgur.com/UIM7GW8.gif)
> docs: Typo fix in the Contribution docs

- docs/contributing/code-of-conduct.md
- docs/contributing/introduction-to-contributing.md
- docs/contributing/triage-guide.md
- docs/introduction.md
- docs/maintainers/check-engines.md
- docs/maintainers/conventional-commit.md
- docs/maintainers/semantic-release.md
- docs/maintainers/setting-up-a-new-repository.md
- docs/technical/dark-mode-explained.md
- docs/technical/fetching-data-from-github.md
- docs/technical/introduction-to-storybook.md
- docs/technical/resolve-merge-conflicts.md
This PR adds [head metadata](https://docusaurus.io/docs/markdown-features/head-metadata) to the markdown files. There are also some auto-linting fixes.
Resolves #45
The head metadata does not affect any visual aspects of the documentation site.
None
https://media.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif
> docs: add head metadata

- .github/workflows/triage.yml
The take action was broken due to these updates
https://github.com/bdougie/take-action/releases/tag/v1.5
> fix: triage.yml

- docs/contributing/introduction-to-contributing.md
https://github.com/open-sauced/hot/pull/456#issuecomment-1482204797
> docs: add lint section to intro to contributing

- docs/community/welcome-to-the-community.md
- docs/contributing/introduction-to-contributing.md
- docs/introduction.md
This PR fixes the Markdown errors found in one of the docs. 
Fixes #106
> fix: revise  markdown errors

- docs/chrome-extension/using-the-chrome-extension.md
Added descriptions for the following sections:
- AI Code Refactoring
- AI Code Test Generation
- AI Code Explanation
- View valuable insights about your GitHub profile
- Invite GitHub users to join OpenSauced with a single click
Please give feedback on the wording. I'm not very good at writing :sweat_smile: 
Fixes: #114
> feat: add more descriptions for using the chrome extension page

- docs/community/faqs.md
- docs/community/highlights.md
- docs/contributing/introduction-to-contributing.md
- docs/introduction.md
- sidebars.js
1. Moved the community section to the top and renamed it as "Getting started"
2. Moved the FAQ and Highlights  sections
These decisions were made live on stream. My assumption is we would want to add a "Insights" or "Product" to host highlights docs later.
closes #104
> feat: rearranges sections for easy consumption

- docs/community/welcome-to-the-community.md
This PR replaces the incorrect YouTube channel link with the correct link in the [Welcome docs](https://docs.opensauced.pizza/community/welcome-to-the-community/#whats-the-opensauced-community-up-to). 
Fixes #120
> fix: update youtube link on docs

- docs/community/100-days-of-oss.md
adding a the repo template and notion template to the documentation
fixes https://github.com/open-sauced/docs/issues/126
> chore: add 100daysofoss template repo

- docs/community/100-days-of-oss.md
This PR updates the documentation for the #100DaysOfOSS challenge. It suggests using our template repositories from GitHub or Notion to record your journey and reflect on what you learn.  This update aims to enhance the experience of participants and encourage them to join the challenge in ways they feel best suit them.
Closes #134
> docs: revise information about templates

- docs/community/100-days-of-oss.md
- docusaurus.config.js
The GH link and Notion link in 100Days was broken.
> fix: fix broken links

- docs/community/welcome-to-the-community.md
Update the link to the "Intro to Open Source Course" in the "Welcome to the Community" documentation to the new URL: https://intro.opensauced.pizza/#/. This course is designed to assist beginners in getting started with open-source contributions. 
Fixes #143
Before:
https://github.com/open-sauced/docs/assets/106407013/7792e794-d96a-4c39-9a70-bca4b57e9968
After:
https://github.com/open-sauced/docs/assets/106407013/6e7bbc0e-1470-44eb-81e3-3a0a903b7067
> fix: Incorrect Link Destination in Documentation

- docs/community/100-days-of-oss.md
Updated the hyperlink in the "100-days-of-oss.md" file to point to the correct document. This change ensures that newcomers to open source can easily access the recommended course and learn more about getting started with open source.
Fixes #147
Before:
https://github.com/open-sauced/docs/assets/106407013/287391f8-610c-4912-b392-e3447293ec17
After:
https://github.com/open-sauced/docs/assets/106407013/287391f8-610c-4912-b392-e3447293ec17
> fix: Documentation Link Misdirection

- docs/community/highlights.md
- docs/community/insights.md
- sidebars.js
I am doing a quick follow-up PR to fix #148 and change the side label to something that gives brief context. 
FYI @CBID2 this will cause conflicts on your PR #137
> fix: the gif

- .github/workflows/compliance.yml
- .github/workflows/development.yml
This PR fixes the development.yml file and updates the compliance.yml file. The changes ensure that the configuration files are up to date and compliant with the required standards. This will improve the overall stability and security of the project.
_Generated using [OpenSauced](https://opensauced.ai/)._
FYI @BekahHW and @CBID2 this willworkflow failures
> fix: workflow.yml

- .vscode/settings.json
- docs/community/100-days-of-oss.md
Updated text in the "The Official Kickoff" section of 100-days-of-oss.md to be more comprehensible for newcomers. This ensures anyone brand new to open source can easily understand the timeline of 100DaysOfOSS. 
- [✔] 📝 Documentation Update
Before text change: 
After text change:
- [✔] 🙅 no, because they aren't needed
- [✔] 📓 docs.opensauced.pizza
> fix: text to be more concise #160

- docs/maintainers/maintainers-guide.md
- docs/maintainers/setting-up-a-new-repository.md
closes #165
- Creates a separate file for being a maintainer
> feat: Add maintainers-guide

- docs/maintainers/maintainers-guide.md
- sidebars.js
I missed adding the link to the sidebar last time. So here's my fix.
> fix: Change title and sidebar

- docs/community/100-days-of-oss.md
- docs/community/faqs.md
- docs/community/highlights.md
This PR enhances the clarity and usability of the #100DaysOfOSS challenge documentation. It introduces clear sections for content creation and project management, providing specific examples for each. 
Fixes #173
Fixes #172 
Fixes #171
Fixes #170 
Fixes #169
> fix: add parallel structure

- docs/features/dev-card.md
closes #219 
This PR resolves the issue of "page not found" for link "PR velocity" in the Dev Card part of the docs. 
I have updated the document with correct link. 
📝 Documentation Update
NA
No
NA
> fix: updated link to PR Velocity 

- sidebars.js
This PR resolves the issue of not being able to start up the application locally.
The following error is thrown
This happening because there is an id referenced in the sidebar file that not longer exists so I removed it and now it runs fine. 
Refers to #225
> fix: remove storybook id from sidebar file

- docs/contributing/set-up-authentication.md
This is a small change to upgrade the v1 API docs to the new v2
---
⚠️ We'll probably want to not merge/deploy this until we do the v1 --> v2 cutover
Closes: https://github.com/open-sauced/docs/issues/238
Related to: https://github.com/open-sauced/api/issues/478
N/a - no other "v1" references for the API found
> feat: Update API docs to v2

- docs/contributing/introduction-to-contributing.md
This PR addresses 2 TODO items in #249 😄
Thank you for the feedback!
- L29-40: Implemented changes based on PR feedback and copy suggestions
- Noticed there was 2 "Code of Conduct" lines that were uncapitalized, so I did both
- L20: Capitalization of "Code of Conduct"
- L37: Capitalization of "Code of Conduct"
Fixes #249 
N/A
N/A
N/A
> fix: Issues Section

- docs/community/100-days-of-oss.md
> fix: Update docs for 100 days of oss

- docs/features/contributor-insights.md
- docs/features/repo-insights.md
- docs/features/workspaces.md
This PR clarifies the visibility of insights pages. Their visibility is tied to their workspace visibility. For individual accounts, they will always be public. For Team (PRO) plans, they can choose.
> chore: clarify visibility of insight pages

- docs/welcome/faqs.md
We've had some questions about auth, so I wanted to add it to the FAQs.
closes #274
> chore: Add FAQ about auth

- docs/contributing/introduction-to-contributing.md
This PR updates contributing guide with the following changes:
- Rewording an instruction to emphasize that creating a new branch is a must.
- Add an information that maintainers may unassign contributors and close their PR if they take more than one `good first issue`.
- Add Docusaurus special admonition syntax to highlight notes, infos, etc.
Closes #287 
1. Pull this branch.
2. Run the project locally.
3. Go to http://localhost:3000/contributing/introduction-to-contributing/
> feat: update contributing guide

- README.md
This PR replaces the old logo in the README.md file with a new one.
Fixes #297 
**the problem** 
**the solution**
> docs: logo readme.md changed to new one

- blog/2024/2024-06-03-how-to-find-open-source-projects-to-contribute-to.md
Adds this weeks post on how to find projects to contribute to.
closes #316 
https://deploy-preview-317--saucedocs.netlify.app/community-resources/how-to-find-open-source-projects-to-contribute-to/
> feat: Add post on how to find open source projects

- blog/2024/2024-06-03-how-to-find-open-source-projects-to-contribute-to.md
I missed a couple of updates in the post.
> fix: description and spacing

- blog/2024/2024-06-03-how-to-find-open-source-projects-to-contribute-to.md
Took a new approach to Monday's post.
> fix: Update post for a new approach

- npm-shrinkwrap.json
- package.json
There was a new version of docusaurus released that solves some bug issues with linking and gives us the ability to use tags in the community-resources blog. This upgrades our current version.
closes #315
> feat: Update docusaurus to latest version

- README.md
- blog/2023/2023-06-21-open-source-101-a-beginners-guide-to-getting-started.md
- blog/2023/2023-07-24-setting-goals-for-your-open-source-contributions.md
- blog/2023/2023-09-05-how-to-participate-in-hacktoberfest.md
- docs/community/100-days-of-oss.md
- docs/contributing/opensauced-maintainers-guide/community-maintainers-guide.md
- docusaurus.config.js
In the spirit of transparency, we're making more space for the community on our GH discussions, so we're updating our docs to reflect that.
closes #318
> fix: Replace discord with Community

- README.md
- removes discord
- removes docusaurus boilerplate
> fix: remove discord and boilerplate

- blog/2024/2024-06-17-valibot-a-new-approach-to-data-validation-in-javascript.md
Brings over https://dev.to/opensauced/valibot-a-new-approach-to-data-validation-in-javascript-1mgb to the docs site.
Relates to #328
1. Ensure the blog post loads at https://deploy-preview-331--saucedocs.netlify.app/community-resources/valibot-a-new-approach-to-data-validation-in-javascript/
> chore: added Nick's valibot blog post

- blog/2023/2023-08-09-caching-git-repos.md
- blog/2023/2023-09-14-how-we-made-our-go-microservice-24x-faster.md
- blog/authors.yml
Adding my blog posts from Dev.to that aren't on opensauced.pizza/blog
N/a - followup to #327 
Posts added:
1. Run docs site with `npm start`
2. Scroll down to older posts in "Community resources"
> feat: Add johns bespoke blog posts

- docs/contributors/contributors-guide.md
- docs/welcome/faqs.md
This adds references to issue comments on the user profile.
closes #336
> feat: add contrib issue comments

- docs/features/repo-pages.md
- docs/welcome/glossary.md
- adds YOLO code to glossary
- adds YOLO coder to repo pages, including insights into why it's important
closes #347
> feat: Add Yolo coder

- blog/2024/2024-07-15-the-react-useref-hook-not-just-for-html-elements.md
Adds my latest blog post, [The React useRef Hook: Not Just for DOM Elements](https://dev.to/opensauced/the-react-useref-hook-not-just-for-html-elements-3cf3), to the community resources.
Note: I've already updated the canonical URL on DEV.
Closes #349
1. Go to https://deploy-preview-350--saucedocs.netlify.app/community-resources/
2. Notice the latest blog post is first blog post and it is truncated with a Read More link.
3. Go to https://deploy-preview-350--saucedocs.netlify.app/community-resources/the-react-useref-hook-not-just-for-html-elements/ to see the full article.
> chore: added my latest blog post from DEV

- blog/2024/2024-07-15-the-react-useref-hook-not-just-for-html-elements.md
Updates a code snippet that's already been updated on dev.to. See this [comment on the DEV post](https://dev.to/nickytonline/comment/2gkg8). Thanks for chiming in @jgarplind!
Relates to #349
N/A
> chore: update blog post

- docs/features/contributor-insights.md
- docs/welcome/glossary.md
The glossary definition for OSCR still said 30 days. This updates that to 90 and provides more insight into what we're looking at. Also, links to the glossary page from the contrib insight page.
closes #366
> fix: oscr glossary def

- docs/community/100-days-of-oss.md
- docs/features/repo-pages.md
- sidebars.js
- adds OSCR to #100Days
- Clarifies OSCR on Repo pages
- collapses a couple of sidebar categories for readability
closes #370 
closes #360
> feat: oscr enhancements

- blog/2024/2024-08-19-supercharge-your-github-profile.md
- blog/2024/supercharge-your-github-profile.md
Adds Nick's latest post on the GH action for Dev Cards
https://deploy-preview-373--saucedocs.netlify.app/community-resources/supercharge-your-github-profile/
> feat: Add nick's post

- blog/2024/2024-02-12-three-open-source-alternatives-to-calendly.md
- updates the calendly alt page for SEO purposes
https://deploy-preview-375--saucedocs.netlify.app/community-resources/three-open-source-alternatives-to-calendly/
> chore: Update Cal.com to link to current OpenSauced pages

- blog/authors.yml
- docusaurus.config.js
- npm-shrinkwrap.json
- package.json
- updates docusaurus
- Adds author pages
closes #365
> feat: upgrade docusaurus

- blog/2024/2024-03-05-collaborate-conquer-grow-mastering-the-art-of-issue-management-for-open-source-projects.md
- blog/2024/2024-04-18-the-missing-piece-why-your-project-needs-a-maintainer-onboarding-process.md
- blog/2024/2024-04-23-the-secret-recipe-to-getting-your-pull-requests-reviewed-and-merged-faster.md
- blog/2024/2024-04-30-building-bridges-not-walls-the-importance-of-documentation-in-open-source-projects.md
- blog/2024/2024-05-09-streamline-your-contributions-mastering-issue-forms-and-pr-templates.md
This PR imports the blog posts written by AdiatiAyu from DEV to OpenSauced.
Closes #378
> feat: import blog posts by AdiatiAyu

- docs/tools/pizza-cli/pizza-action.md
Updates to the latest action number.
closes #388
> fix: Update action version to reflect update and remove bug

- .github/workflows/pizza-action.yml
Updates the pizza action to the latest version.
Relates ti #386
> chore: update pizza action

- docs/contributing/opensauced-writers-guide/how-to-add-your-post.md
Updated authors.yml example based on [docusaurus 3.5](https://docusaurus.io/blog/releases/3.5)
closes #383 
1. Go to Contributing tab
2. click OpenSauced Writers Guide
> docs: update authors guide with Docusaurus 3.5 changes

- .sauced.yaml
- CODEOWNERS
- updates emails for me and Ayu
- adds fallback attribution
- updates codeowners
closes #400
> fix: sauced.yaml to use userid as part of email

- docs/contributors/contributors-guide.md
- docs/maintainers/understanding-repo-insights.md
Some grammatical fixes
Closes #399
> fix: correct grammar
